'use strict';
const $=id=>document.getElementById(id);let token='',rows=[],selected=null,verifiedHead=null;
const statuses=['COMPLIANT','VIOLATION','INSUFFICIENT_EVIDENCE','NOT_APPLICABLE'];
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function filtered(){const q=$('search').value.toLowerCase();return rows.filter(r=>(!$('status').value||r.compliance===$('status').value)&&(!$('scenario').value||r.scenario===$('scenario').value)&&(!$('agent').value||r.agent_id===$('agent').value)&&(!$('severity').value||r.severity===$('severity').value)&&JSON.stringify(r).toLowerCase().includes(q));}
function render(){const visible=filtered();$('cards').replaceChildren();for(const s of ['TOTAL',...statuses]){const c=node('div','','card');c.append(node('small',s.replaceAll('_',' ')),node('strong',String(s==='TOTAL'?visible.length:visible.filter(r=>r.compliance===s).length)));$('cards').append(c);}$('rows').replaceChildren();for(const r of visible){const tr=node('tr','');tr.append(node('td',new Date(r.created_at_ns/1e6).toLocaleString()),node('td',r.agent_id.slice(0,10)+' / '+r.interaction_id.slice(0,12)));const status=node('td','');status.append(node('span',r.compliance,'badge '+r.compliance));tr.append(status,node('td',verifiedHead?'PASS (snapshot)':'NOT RUN'),node('td',r.scenario.replaceAll('_',' ')));const td=node('td',''),button=node('button','Inspect');button.onclick=()=>detail(r);td.append(button);tr.append(td);$('rows').append(tr);}if(!visible.length){const tr=node('tr',''),td=node('td','No matching observations. Submit samples through the observation API.');td.colSpan=6;tr.append(td);$('rows').append(tr);}}
function detail(r){selected=r;$('overview').replaceChildren();for(const [k,v] of Object.entries({compliance:r.compliance,integrity:verifiedHead?'PASS for verified snapshot':'NOT_RUN',evidence:r.evidence_id,policy_hash:r.policy_hash,policy_version_reference:r.policy_version,source_independence:r.source_independence})){const p=node('p',k+': '+v);$('overview').append(p);}$('checks').textContent=JSON.stringify({checks:r.checks,requirements:r.requirements,availability:r.availability},null,2);$('json').textContent=JSON.stringify(r,null,2);$('comparison').replaceChildren();for(const other of rows.filter(x=>x.correlation_id===r.correlation_id))$('comparison').append(node('p',other.scenario+' / '+other.compliance+' / '+other.interaction_id.slice(0,12)));$('detail').showModal();}
async function refresh(){try{$('message').textContent='Loading observations…';verifiedHead=null;$('integrity').textContent='Not run for the refreshed snapshot.';const data=await api('/results');rows=data.results;const policies=await api('/policies');$('policies').replaceChildren();for(const p of policies.policies)$('policies').append(node('pre',JSON.stringify(p,null,2)));const previous=$('agent').value;$('agent').replaceChildren(new Option('All agents',''));for(const id of [...new Set(rows.map(r=>r.agent_id))])$('agent').add(new Option(id.slice(0,12),id));$('agent').value=previous;render();$('message').textContent='Identifiers are pseudonymized. Payloads are withheld from this interface.';}catch(e){rows=[];render();$('message').textContent=e.message;}}
$('connect').onclick=()=>{token=$('token').value;$('token').value='';refresh();};$('refresh').onclick=refresh;for(const id of ['search','status','scenario','agent','severity'])$(id).oninput=render;
$('close').onclick=()=>$('detail').close();$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(selected,null,2));$('copy').textContent='Copied';}catch{$('copy').textContent='Select and copy JSON below';}};
$('verify').onclick=async()=>{try{$('verify').disabled=true;verifiedHead=null;const result=await api('/verify',{});const latest=await api('/results');rows=latest.results;const head=rows.at(-1)?.evidence_hash;verifiedHead=result.status==='PASS'&&head===result.head?head:null;$('integrity').textContent=JSON.stringify(result)+(verifiedHead?'':' • No verified row snapshot assigned.');render();}catch(e){$('integrity').textContent=e.message;verifiedHead=null;render();}finally{$('verify').disabled=false;}};render();
